// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzjnbcjdxfwxerbhskjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56am5iY2pkeGZ3eGVyYmhza2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNjQ3MjMsImV4cCI6MjA1MTc0MDcyM30.rBbS3qrbxyZbph4XSrZR4clmGTHrje3ztq0lYjgdalg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);